import SwiftUI

// Generated by Supernova - do not modify manually
struct AppMeasures {

    static let small = 10 
    static let ref = 5 
    static let base = 5 
    static let smallNegative = -5 
    static let toggleNegative = -1 
}