import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func borderBase() -> some View {
        return self.border(Color(.sRGB, red: 94/255, green: 25/255, blue: 144/255, opacity: 1), width: 1) 
    }

    func borderRef() -> some View {
        return self.border(Color(.sRGB, red: 94/255, green: 25/255, blue: 144/255, opacity: 1), width: 1) 
    }
}