import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        let random = Color(.sRGB, red: 94/255, green: 25/255, blue: 144/255, opacity: 1) 
        let test = Color(.sRGB, red: 166/255, green: 85/255, blue: 85/255, opacity: 1) 
        let testFromSmallImport = Color(.sRGB, red: 39/255, green: 53/255, blue: 185/255, opacity: 1) 
    }
}