import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {

    func textStyleBase() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    func textStyleTest() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: -1) 
            .underline() 
            .textCase(.uppercase) 
    }
}