import SwiftUI

// Generated by Supernova - do not modify manually
extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        let base = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 38/255, green: 49/255, blue: 195/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 72/255, green: 18/255, blue: 132/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )

        let ref = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 38/255, green: 49/255, blue: 195/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 72/255, green: 18/255, blue: 132/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )
    }
}