import SwiftUI

// Generated by Supernova - do not modify manually
extension View {  

    func borderBase() -> some View {
        return self.cornerRadius(10) 
    }

    func borderRef() -> some View {
        return self.cornerRadius(10) 
    }
}