import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func shadowBase() -> some View {
        return self.shadow(Color(.sRGB, red: 94/255, green: 25/255, blue: 144/255, opacity: 1), radius: 5, x: 3, y: 7) 
    }

    func shadowRef() -> some View {
        return self.shadow(Color(.sRGB, red: 94/255, green: 25/255, blue: 144/255, opacity: 1), radius: 5, x: 3, y: 7) 
    }
}